### ISSUE TITLE
Program not working.

### ISSUE THREAD

**Issue by YildirimMesut** [JoelGMSec/Invoke-Stealth#4]
I was using this program for 6-5 months but recently, you program is not working. it doesnt obfuscate anything.

![image](https://github.com/JoelGMSec/Invoke-Stealth/assets/94446353/4c93857a-7044-402b-8378-12a3ba9905cc)

**Comment by Kinny092** [comment]
@YildirimMesut Hey, I have the same issue too but when I try to copy all the contents of commit b91145b and replace it in the main file, it starts to do all its functions. Until I understand all the changes he tried to make, I may realise what bug nuked the whole script.

**Comment by JoelGMSec** [comment]
Tested right now and works like a charm on Windows and Linux, without any change:

![image](https://github.com/JoelGMSec/Invoke-Stealth/assets/34335312/ca403ecd-d550-4aa6-b5d9-ceccc882df2d)
![image](https://github.com/JoelGMSec/Invoke-Stealth/assets/34335312/87dc8814-e9ab-45b5-a2d8-375440e329ed)
![image](https://github.com/JoelGMSec/Invoke-Stealth/assets/34335312/ca74e3b8-aae9-496e-af02-9ec0cf1cf943)
![image](https://github.com/JoelGMSec/Invoke-Stealth/assets/34335312/7c804db4-7790-4220-b811-3a22efd5e821)

**Comment by Kinny092** [comment]
@JoelGMSec Confirming it is working. The difference I can see was before I used -technique All and that did not work, now I used -t all and it works. Also when I run it in native PS, I get the below error, but when I run it in ISE, it works perfectly. 
![image](https://github.com/JoelGMSec/Invoke-Stealth/assets/25901267/ee98e408-9b13-4f66-ade0-c5c4ed968d67)

**Comment by JoelGMSec** [comment]
Thanks for the update, I will check and fix it as soon as possible.
In the meantime, keep this in mind :)

Regards!

**Comment by Kinny092** [comment]
you welcome, also do a few test with different ps scripts as I have a hunch that some rng may upset one or more functions. sometimes it does not encrypt anything, sometimes it encrypts but dosent run. for example, it works when the invoke expression is broken into "in"+"vO"+"ke"+"-e"+"xp"+"rE"+"Ss"+"Io"+"N" but it dosent work when its broken into "iNv"+"OkE"+"-eX"+"PrE"+"SSI"+"On" 

![image](https://github.com/JoelGMSec/Invoke-Stealth/assets/25901267/2c109d74-85f2-4533-8b30-9dce72e5531b)

lovely work though, im starting to love it so much.

**Comment by aneesurrehman001** [comment]
The script is not working whether I use "-technique" or "-t". 

![image](https://github.com/JoelGMSec/Invoke-Stealth/assets/55150455/bfbe2889-bce2-41a6-b3ff-ffab30ba936d)

The first line contains empty string though I am assuming it should contain encrypted file content in it.

Also I get no errors when I execute the script. I have python 3.11 installed on my local (Windows 11 Pro) machine.

**Comment by LOLCATATONIA** [comment]
Same error here. I believe the problem lies in the usage of ReverseB64 and it is Windows specific. The script works on Kali. Reverting Invoke-Stealth.ps1to previous versions does nothing.

**Comment by ameily** [comment]
I ran into the exact same problem on Windows and for me the fix was to pass in the absolute path to the input script.

```powershell
# does not work on Windows
Invoke-Stealth.ps1 RunMe.ps1 -Technique All

# this does work on Windows
Invoke-Stealth.ps1 $pwd\RunMe.ps1 -Technique All
```

**Comment by mvthul** [comment]
![image](https://github.com/JoelGMSec/Invoke-Stealth/assets/53946558/539d83cc-1d4d-4f83-926b-5acf2b010d42)

Anyone got it working on Linux pwsh?

**Comment by kaguya3311** [comment]
> I ran into the exact same problem on Windows and for me the fix was to pass in the absolute path to the input script.
> 
> ```powershell
> # does not work on Windows
> Invoke-Stealth.ps1 RunMe.ps1 -Technique All
> 
> # this does work on Windows
> Invoke-Stealth.ps1 $pwd\RunMe.ps1 -Technique All
> ```

This Fix Worked for me!

**Comment by JoelGMSec** [comment]
Closed because it worked without problems as @reggietorres says :)
